#!/bin/bash

# Colors
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
L_BLUE="\e[94m"
ENDCOLOR="\e[0m"

# OS check
if [[ ! -f /etc/os-release ]]; then
    echo "Could not identify OS. Exiting."
    exit 1
fi

# Required binaries
binary_array=("df" "du")
for binary in "${binary_array[@]}"; do
    which "$binary" >/dev/null 2>&1 || { echo -e "${RED}Binary not found - $binary - Exiting.${ENDCOLOR}" >&2; exit 1; }
done

# Go directly to disk analysis
echo -e "\n${YELLOW}--- DISK USAGE ANALYSIS ---${ENDCOLOR}"
read -rp "Please input your name: " admin_name

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

. "$DIR/source/disk/disk.sh"
